### ISSUE TITLE
.NET .dll dependencies

### ISSUE THREAD

**Issue by ikonomov** [fgimian/totalmix-volume-control#6]
Please consider pulling out all the .dll dependencies that are part of the .NET runtime from the install build.  You can just provide a link to the .net runtime that is needed in the description of every release.  There will always be people that will encounter issues and complain no matter what, as you have seen in the RME forum.  They will just have to read the instructions or ask for help, unfortunately this can't be prevented.

**Comment by fgimian** [comment]
> Please consider pulling out all the .dll dependencies that are part of the .NET runtime from the install build. You can just provide a link to the .net runtime that is needed in the description of every release. There will always be people that will encounter issues and complain no matter what, as you have seen in the RME forum. They will just have to read the instructions or ask for help, unfortunately this can't be prevented.

This is how I initially distributed the application but got too many questions about the correct approach to use for installing the runtime, so I since started embedding it. I think I'll keep it as is for now to avoid such confusion. The download size is still relatively small even with the runtime embedded.

I'll consider providing separate downloads in future although that may cause further confusion.

Cheers
Fotis

**Comment by ikonomov** [comment]
You know, there are 3 very good alternatives to what you have done:
1. Provide the .NET runtime install link in the release's description.  Simply say "Install first [link](https://aka.ms/dotnet/8.0/windowsdesktop-runtime-win-x64.exe)"
2. Use an installer package and include the .NET installer in it.
3. Use a version of .NET that is already installed with the current updates for the oldest Windows still supported.  This would be 4.5  in Windows 10.  You are already using optimizations for 8.0, so I'm not suggesting that you should do this, but if you absolutely want to make sure that your installer is "bullet proof" this is the way to do it.

**Comment by fgimian** [comment]
> You know, there are 3 very good alternatives to what you have done:
> 
>     1. Provide the .NET runtime install link in the release's description.  Simply say "Install first [link](https://aka.ms/dotnet/8.0/windowsdesktop-runtime-win-x64.exe)"
> 
>     2. Use an installer package and include the .NET installer in it.
> 
>     3. Use a version of .NET that is already installed with the current updates for the oldest Windows still supported.  This would be 4.5  in Windows 10.  You are already using optimizations for 8.0, so I'm not suggesting that you should do this, but if you absolutely want to make sure that your installer is "bullet proof" this is the way to do it.

Thanks for the ideas, here's my feedback on each:

1. I will consider this as long as I offer both versions for download (one with .NET included and one without). You are the first one to bring this up since I started embedding the runtime, so I don't think I'll pursue this unless I get further requests as it doesn't bother me personally. A 50 MB installer is really nothing, apps like Obsidian, VS Code, Discord and Todoist which bundle Electron are all > 70 MB.

2. I'm not aware of a way to do this elegantly and am not fan of installers that run other installers, especially for automation purposes (e.g. silent installs) which I use when automating my Windows install.

3. .NET Framework is legacy now and only in maintenance mode, I use features of the latest .NET release in my app and want the latest and greatest features and optimisations that the .NET team has to offer. Microsoft themselves use the latest .NET for PowerShell and other modern apps they write in C#. At some point, .NET Framework 4.5 will unboundetly stop shipping with Windows and become unsupported much like 2.0 was recently.

I'll be closing this issue for now and watching out for other requests like this, in which case I will consider the first option again. I have been pursuing a rewrite in Rust in the background which is my ultimate end-goal now, but I'm still not entirely happy with what I have so far.

If you have your heart set on it, you are welcome to create your own build without the runtime. You can see the commit https://github.com/fgimian/totalmix-volume-control/commit/d9eba3acbf8ad61a64520d089604b2b839518781 which switched to a self-contained build to see what you would need to do.

Cheers
Fotis
